name: Deploy Theme

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repo
        uses: actions/checkout@v4

      - name: Deploy Ghost theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}